/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ocl1_proyecto1;

import Analizadores.Analizador_Lexico;
import Objetos.Expresiones;
import Analizadores.Sintactico;
import Errores.ErroresS;
import Objetos.AFD;
import Objetos.AFND;
import Objetos.Conjuntos;
import Objetos.Encabezado;
import Objetos.Imagenes;
import Objetos.ListaCircular;
import Objetos.NSiguiente;
import Objetos.NTrancisiones;
import Objetos.NodoImagenes;
import Objetos.TSiguiente;
import Objetos.TTransiciones;
import Objetos.Validaciones;
import java.awt.Desktop;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author feral
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    String path;
    public static ArrayList<ErroresS> listErrors = new ArrayList<ErroresS>();
    public static LinkedList<Validaciones> lista_val = new LinkedList<Validaciones>();
    public static ListaCircular afd = new ListaCircular();
    public static ListaCircular afnd = new ListaCircular();
    public static ListaCircular siguientes = new ListaCircular();
    public static ListaCircular transiciones = new ListaCircular();
    public static ListaCircular arboles = new ListaCircular();
    public static Encabezado encabezado = new Encabezado();
    public static LinkedList<Conjuntos> conjunt = new  LinkedList<Conjuntos>();

    DefaultMutableTreeNode grafi = new DefaultMutableTreeNode("Graficos");
    DefaultMutableTreeNode afdn = new DefaultMutableTreeNode("AFD");
    DefaultMutableTreeNode afndn = new DefaultMutableTreeNode("AFND");
    DefaultMutableTreeNode siguientesn = new DefaultMutableTreeNode("Siguientes");
    DefaultMutableTreeNode trancisionesn = new DefaultMutableTreeNode("Trancisiones");
    DefaultMutableTreeNode arbolesn = new DefaultMutableTreeNode("Arboles");
    DefaultTreeModel root = new DefaultTreeModel(grafi);
    public NodoImagenes supimg;
    Icon icono;

    public Interface() {

        initComponents();
        jComboBox1.disable();
        jTextArea1.setEnabled(false);

        grafi.add(afdn);
        grafi.add(afndn);
        grafi.add(siguientesn);
        grafi.add(trancisionesn);
        grafi.add(arbolesn);
        jTree1.setModel(root);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        label1.setText("label1");

        label2.setText("label2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Archivos de Entrada: ");

        jButton1.setText("Guardar Automáta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Analizar Entrada");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Arboles", "Siguientes", "Transiciones", "AFD", "AFND" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setText("Atras");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Siguiente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jScrollPane5.setViewportView(jTree1);

        jMenuBar1.setBorder(null);

        jMenu1.setText("File");

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Guardar Como");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(114, 114, 114))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filtroImagen = new FileNameExtensionFilter("OCL(.ocl)", "ocl");
        fileChooser.setFileFilter(filtroImagen);
        fileChooser.setDialogTitle("Specify a file to save");
        fileChooser.showSaveDialog(null);

        try {
            path = fileChooser.getSelectedFile().getAbsolutePath();
            File f = fileChooser.getSelectedFile();
            BufferedReader bf = new BufferedReader(new FileReader(f));
            String l = bf.readLine();
            while (l != null) {
                jTextArea1.append(l + "\n");
                l = bf.readLine();

            }
        } catch (Exception e) {
        }
        jTextArea1.setEnabled(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public static void generarReporteHTML() throws IOException {
        FileWriter fichero = null;
        PrintWriter pw = null;
        try {
            String path = "ERRORES_201900528\\Reporteerrores.html";
            fichero = new FileWriter(path);
            pw = new PrintWriter(fichero);
            //comenzamos a escribir el html
            pw.println("<html>");
            pw.println("<head><title>REPORTE DE ERRORES</title></head>");
            pw.println("<body>");
            pw.println("<div align=\"center\">");
            pw.println("<h1>Reporte de Errores</h1>");
            pw.println("<br></br>");
            pw.println("<table border=1>");
            pw.println("<tr>");
            pw.println("<td>ERROR</td>");
            pw.println("<td>DESCRIPCION</td>");
            pw.println("<td>FILA</td>");
            pw.println("<td>COLUMNA</td>");
            pw.println("</tr>");
            for (int i = 0; i < listErrors.size(); i++) {
                pw.println("<tr>");
                pw.println("<td>" + listErrors.get(i).getTipo() + "</td>");
                pw.println("<td>" + listErrors.get(i).getDescripcion() + "</td>");
                pw.println("<td>" + listErrors.get(i).getFila() + "</td>");
                pw.println("<td>" + listErrors.get(i).getColumna() + "</td>");
                pw.println("</tr>");
            }
            pw.println("</table>");
            pw.println("</div");
            pw.println("</body>");
            pw.println("</html>");
            //Desktop.getDesktop().open(new File(path));
        } catch (Exception e) {
        } finally {
            if (null != fichero) {
                fichero.close();
            }
        }
        try {

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        File saving = new File(path);
        try (FileWriter guardado = new FileWriter(saving)) {
            guardado.write(jTextArea1.getText());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            JFileChooser archivo = new JFileChooser(System.getProperty("user.dir"));
            archivo.showSaveDialog(this);
            if (archivo.getSelectedFile() != null) {
                try (FileWriter guardado = new FileWriter(archivo.getSelectedFile())) {
                    guardado.write(jTextArea1.getText());
                    JOptionPane.showMessageDialog(rootPane, "El archivo fue guardado con éxito en la ruta establecida");
                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            //se ejecuta el lexico y sintactico.
            Sintactico sintactico = new Sintactico(new Analizador_Lexico(new BufferedReader(new StringReader(jTextArea1.getText()))));
            sintactico.parse();
            generarReporteHTML();
            System.out.println("Todo bien, todo correcto :)");

            LinkedList<Object> enca = sintactico.enca;
            lista_val = sintactico.lista_valida;
            for (int i = 0; i < enca.size(); i++) {
                System.out.println("Expresion " + i);
                Expresiones aux = new Expresiones(null, null, null);
                Conjuntos auxc = new Conjuntos(null, null, null);
                try {
                    aux = (Expresiones) enca.get(i);
                    auxc = (Conjuntos)enca.get(i);
                    if (aux != null && aux.type == "Expresion") {
                        aux.getArbol().GraficarSintactico();
                        ImageIcon a = new ImageIcon("ARBOLES_201900528\\" + aux.id + ".jpg");
                        Imagenes sup = new Imagenes(aux.id, "ARBOLES_201900528\\" + aux.id + ".jpg");
                        sup.imagen = a;
                        this.arboles.add(sup);

                        aux.recorridoPreorden();
                        TSiguiente aux2 = new TSiguiente(aux.hojitas, aux.id);
                        aux.setTablita(aux2);
                        aux.getTablita().GenerarTablita();
                        ImageIcon a2 = new ImageIcon("SIGUIENTES_201900528\\Siguientes" + aux.id + ".jpg");
                        Imagenes sup2 = new Imagenes(aux.id, "SIGUIENTES_201900528\\Siguientes" + aux.id + ".jpg");
                        sup2.imagen = a2;
                        this.siguientes.add(sup2);
                        LinkedList<NTrancisiones> nodito = new LinkedList<NTrancisiones>();
                        TTransiciones tablita = new TTransiciones(aux.getArbol().raiz.primeros, aux.getTablita().nodes, aux.id, nodito);
                        aux.setTablitatransi(tablita);
                        aux.getTablitatransi().GraphTablita();
                        ImageIcon a3 = new ImageIcon("TRANCISIONES_201900528\\Transicion" + aux.id + ".jpg");
                        Imagenes sup3 = new Imagenes(aux.id, "TRANCISIONES_201900528\\Transicion" + aux.id + ".jpg");
                        sup3.imagen = a3;
                        this.transiciones.add(sup3);
                        aux.setAfedesito(new AFD(aux.getTablitatransi().tablona, aux.id, aux.getTablitatransi().estados));
                        aux.getAfedesito().GraphAfd();
                        ImageIcon a4 = new ImageIcon("AFD_201900528\\AFD" + aux.id + ".jpg");
                        Imagenes sup4 = new Imagenes(aux.id, "AFD_201900528\\AFD" + aux.id + ".jpg");
                        sup4.imagen = a4;
                        this.afd.add(sup4);
                        aux.recorridoPostorden();
                        aux.setAfede(new AFND(aux.id, aux.hojitasafnd));
                        DefaultMutableTreeNode support = new DefaultMutableTreeNode(aux.id);
                        DefaultMutableTreeNode support2 = new DefaultMutableTreeNode(aux.id);
                        DefaultMutableTreeNode support3 = new DefaultMutableTreeNode(aux.id);
                        DefaultMutableTreeNode support4 = new DefaultMutableTreeNode(aux.id);
                        DefaultMutableTreeNode support5 = new DefaultMutableTreeNode(aux.id);
                        this.arbolesn.add(support);
                        this.afdn.add(support2);
                        this.siguientesn.add(support3);
                        this.afndn.add(support4);
                        this.trancisionesn.add(support5);

                        this.root.reload();

                    }else if (auxc != null && aux.type == "Conjunto"){
                        this.conjunt.add(auxc);
                    
                    }
                } catch (Exception e) {
                }

            }
            //System.out.println("Hola :)");

        } catch (Exception ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        jComboBox1.enable();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String g = jComboBox1.getSelectedItem().toString();
        Imagenes sup;
        switch (g) {

            case "AFD":
                sup = this.afd.cabeza.getImage();
                icono = new ImageIcon(sup.imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
                jLabel2.setIcon(icono);
                jLabel3.setText(sup.name);
                supimg = this.afd.cabeza;
                break;
            case "AFND":
                sup = this.afnd.cabeza.getImage();
                icono = new ImageIcon(sup.imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
                jLabel2.setIcon(icono);
                jLabel3.setText(sup.name);
                supimg = this.afnd.cabeza;
                break;
            case "Transiciones":
                sup = this.transiciones.cabeza.getImage();
                icono = new ImageIcon(sup.imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
                jLabel2.setIcon(icono);
                jLabel3.setText(sup.name);
                supimg = this.transiciones.cabeza;
                break;
            case "Siguientes":
                sup = this.siguientes.cabeza.getImage();
                icono = new ImageIcon(sup.imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
                jLabel2.setIcon(icono);
                jLabel3.setText(sup.name);
                supimg = this.siguientes.cabeza;
                break;
            case "Arboles":
                sup = this.arboles.cabeza.getImage();
                icono = new ImageIcon(sup.imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
                jLabel2.setIcon(icono);
                jLabel3.setText(sup.name);
                supimg = this.arboles.cabeza;
                break;

        }
        System.out.println("hola");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
            NodoImagenes support = supimg;
            icono = new ImageIcon(support.getNext().getImage().imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
            jLabel2.setIcon(icono);
            jLabel3.setText(support.getNext().getImage().name);
            supimg = support.getNext();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            NodoImagenes support = supimg;
            icono = new ImageIcon(support.getBack().getImage().imagen.getImage().getScaledInstance(jLabel2.getWidth(), jLabel2.getHeight(), Image.SCALE_DEFAULT));
            jLabel2.setIcon(icono);
            jLabel3.setText(support.getBack().getImage().name);
            supimg = support.getBack();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTree jTree1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
