
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int cadena = 20;
  public static final int conca = 5;
  public static final int mayork = 12;
  public static final int coma = 25;
  public static final int conj = 19;
  public static final int or = 6;
  public static final int guion = 11;
  public static final int ptcoma = 16;
  public static final int cmllsmpl = 22;
  public static final int digito = 2;
  public static final int cmlldbl = 23;
  public static final int EOF = 0;
  public static final int letra = 3;
  public static final int id = 24;
  public static final int corchec = 10;
  public static final int sltln = 21;
  public static final int cierre = 7;
  public static final int esp = 4;
  public static final int corchea = 9;
  public static final int error = 1;
  public static final int curv = 17;
  public static final int inte = 18;
  public static final int dspts = 15;
  public static final int mas = 8;
  public static final int prct = 14;
  public static final int menork = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "digito",
  "letra",
  "esp",
  "conca",
  "or",
  "cierre",
  "mas",
  "corchea",
  "corchec",
  "guion",
  "mayork",
  "menork",
  "prct",
  "dspts",
  "ptcoma",
  "curv",
  "inte",
  "conj",
  "cadena",
  "sltln",
  "cmllsmpl",
  "cmlldbl",
  "id",
  "coma"
  };
}

